# Data Extraction

In [8]:
import pandas as pd
messages = pd.read_csv('SMSSpamCollection', sep='\t', names = ['labels', 'message'])

In [9]:
messages

labels                                            message
0       ham  Go until jurong point, crazy.. Available only ...
1       ham                      Ok lar... Joking wif u oni...
2      spam  Free entry in 2 a wkly comp to win FA Cup fina...
3       ham  U dun say so early hor... U c already then say...
4       ham  Nah I don't think he goes to usf, he lives aro...
...     ...                                                ...
5567   spam  This is the 2nd time we have tried 2 contact u...
5568    ham               Will ü b going to esplanade fr home?
5569    ham  Pity, * was in mood for that. So...any other s...
5570    ham  The guy did some bitching but I acted like i'd...
5571    ham                         Rofl. Its true to its name

[5572 rows x 2 columns]

# Data Cleaning and Preprocessing

In [6]:
import re
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     /Users/anithabalachandran/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [91]:
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
lemmatizer = WordNetLemmatizer()
from nltk.stem import PorterStemmer
stemmer = PorterStemmer()


In [92]:
corpus = []
for i in range(len(messages)):
    review = re.sub('[^a-zA-Z]', ' ', messages['message'][i])
    review = review.lower()
    review = review.split()
    review = [stemmer.stem(word) for word in review if not word in stopwords.words('english')]
    review = ' '.join(review)
    corpus.append(review)
    
    

In [93]:
corpus

['go jurong point crazi avail bugi n great world la e buffet cine got amor wat',
 'ok lar joke wif u oni',
 'free entri wkli comp win fa cup final tkt st may text fa receiv entri question std txt rate c appli',
 'u dun say earli hor u c alreadi say',
 'nah think goe usf live around though',
 'freemsg hey darl week word back like fun still tb ok xxx std chg send rcv',
 'even brother like speak treat like aid patent',
 'per request mell mell oru minnaminungint nurungu vettam set callertun caller press copi friend callertun',
 'winner valu network custom select receivea prize reward claim call claim code kl valid hour',
 'mobil month u r entitl updat latest colour mobil camera free call mobil updat co free',
 'gonna home soon want talk stuff anymor tonight k cri enough today',
 'six chanc win cash pound txt csh send cost p day day tsandc appli repli hl info',
 'urgent week free membership prize jackpot txt word claim c www dbuk net lccltd pobox ldnw rw',
 'search right word thank breather

# Handle Dependent Feature

In [94]:
y = pd.get_dummies(messages['labels'])
y

ham   spam
0      True  False
1      True  False
2     False   True
3      True  False
4      True  False
...     ...    ...
5567  False   True
5568   True  False
5569   True  False
5570   True  False
5571   True  False

[5572 rows x 2 columns]

In [95]:
y=y.iloc[:,0].values
y

array([ True,  True, False,  True,  True, False,  True,  True, False, False,  True, False, False,  True,  True, False,  True,  True,  True, False,  True,  True,  True,  True,  True,  True,  True,  True,  True,  True, ...,  True,  True,  True,  True,  True, False,  True,  True,  True,  True,  True,  True,  True,  True,  True,  True,  True,  True,  True,  True,  True,  True,  True,  True, False, False,  True,  True,  True,  True])

In [96]:
# Train Test Split

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(corpus, y, test_size=0.2, random_state=42)


In [97]:
print(len(X_train), len(X_test))

4457 1115


In [98]:
X_train

['repli win weekli fifa world cup held send stop end servic',
 'hello sort town alreadi dont rush home eat nacho let know eta',
 'come guoyang go n tell u told',
 'hey sathya till dint meet even singl time saw situat sathya',
 'orang bring rington time chart hero free hit week go rington pic wap stop receiv tip repli stop',
 'sit mu wait everyon get suit take shower',
 'finish liao u',
 'urgent mobil award bonu caller prize nd attempt contact call box qu',
 'probabl still go stuff',
 'wah lucki man save money hee',
 'hey u still gym',
 'oh lk tt den take e one tt end cine lor dun wan yogasana oso',
 'ok lor',
 'still havent collect dough pl let know go place sent get control number',
 'stupid possibl',
 'u secret admir reveal think u r special call opt repli reveal stop per msg recd cust care',
 'amaz rearrang letter give mean dormitori dirti room astronom moon starer eye see elect result lie let recount mother law woman hitler eleven plu two twelv plu one amaz',
 'call listen extrem d

# Create Bag Of Words

In [99]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features=2500, ngram_range=(1,2))


In [100]:
# Handling Independent Features
X_train = cv.fit_transform(X_train).toarray()
X_test = cv.transform(X_test).toarray()
print(X_train.shape, X_test.shape)

(4457, 2500) (1115, 2500)


In [101]:
import numpy as np
np.set_printoptions(edgeitems=30, linewidth=100000, 
    formatter=dict(float=lambda x: "%.3g" % x))
X_train

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0

In [102]:
cv.vocabulary_

{'repli': 1724,
 'win': 2398,
 'weekli': 2372,
 'world': 2433,
 'cup': 461,
 'send': 1827,
 'stop': 1993,
 'end': 591,
 'servic': 1843,
 'send stop': 1833,
 'stop end': 1995,
 'hello': 914,
 'sort': 1944,
 'town': 2180,
 'alreadi': 48,
 'dont': 545,
 'rush': 1770,
 'home': 950,
 'eat': 578,
 'let': 1143,
 'know': 1087,
 'let know': 1145,
 'come': 385,
 'go': 792,
 'tell': 2071,
 'told': 2157,
 'hey': 917,
 'till': 2134,
 'dint': 530,
 'meet': 1281,
 'even': 616,
 'singl': 1885,
 'time': 2135,
 'saw': 1791,
 'situat': 1893,
 'orang': 1505,
 'bring': 213,
 'rington': 1750,
 'chart': 325,
 'free': 708,
 'hit': 931,
 'week': 2363,
 'pic': 1564,
 'wap': 2340,
 'receiv': 1701,
 'repli stop': 1729,
 'sit': 1891,
 'mu': 1374,
 'wait': 2318,
 'everyon': 624,
 'get': 762,
 'suit': 2022,
 'take': 2050,
 'shower': 1869,
 'finish': 681,
 'liao': 1147,
 'urgent': 2273,
 'mobil': 1328,
 'award': 118,
 'bonu': 189,
 'caller': 268,
 'prize': 1644,
 'nd': 1396,
 'attempt': 107,
 'contact': 413,
 'call':

# Modeling

In [103]:
from sklearn.naive_bayes import MultinomialNB
mnb_model = MultinomialNB().fit(X_train, y_train)
mnb_model

MultinomialNB()

# Prediction

In [104]:
y_pred = mnb_model.predict(X_test)

In [105]:
from sklearn.metrics import accuracy_score, classification_report
score=accuracy_score(y_test,y_pred)

print(f"Accuracy: {score}")

Accuracy: 0.9838565022421525


In [106]:
print(classification_report(y_pred, y_test))

              precision    recall  f1-score   support

       False       0.93      0.95      0.94       145
        True       0.99      0.99      0.99       970

    accuracy                           0.98      1115
   macro avg       0.96      0.97      0.96      1115
weighted avg       0.98      0.98      0.98      1115



# Creating The TF-IDF Model


In [107]:
## Train Test Split
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(corpus,y,test_size=0.20)

In [108]:
from sklearn.feature_extraction.text import TfidfVectorizer
tv=TfidfVectorizer(max_features=2500,ngram_range=(1,2))
X_train=tv.fit_transform(X_train).toarray()
X_test=tv.transform(X_test).toarray()

In [109]:
X_train

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.52, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0

In [110]:
tv.vocabulary_

{'ard': 87,
 'like': 1168,
 'dat': 483,
 'lor': 1206,
 'like dat': 1169,
 'hmmm': 952,
 'guess': 886,
 'go': 800,
 'kb': 1087,
 'power': 1636,
 'yoga': 2493,
 'haha': 894,
 'dunno': 573,
 'thk': 2117,
 'got': 843,
 'oso': 1530,
 'forgot': 711,
 'liao': 1160,
 'bu': 215,
 'leav': 1145,
 'lt': 1236,
 'gt': 865,
 'lt gt': 1238,
 'freak': 717,
 'meet': 1299,
 'depend': 516,
 'wan': 2325,
 'phone': 1576,
 'gonna': 825,
 'die': 525,
 'stay': 1989,
 'receiv': 1716,
 'week': 2365,
 'rington': 1768,
 'shortli': 1874,
 'enjoy': 601,
 'releas': 1732,
 'shirt': 1867,
 'put': 1674,
 'make': 1262,
 'half': 898,
 'nake': 1405,
 'instead': 1034,
 'white': 2388,
 'dinner': 533,
 'urgent': 2269,
 'tri': 2185,
 'contact': 412,
 'today': 2148,
 'draw': 559,
 'show': 1876,
 'prize': 1658,
 'guarante': 877,
 'call': 231,
 'land': 1113,
 'line': 1174,
 'claim': 347,
 'valid': 2291,
 'hr': 986,
 'urgent tri': 2274,
 'tri contact': 2186,
 'contact today': 416,
 'today draw': 2150,
 'draw show': 560,
 'show pri

In [111]:
from sklearn.naive_bayes import MultinomialNB
spam_tfidf_model = MultinomialNB().fit(X_train, y_train)

In [112]:
#prediction
y_pred=spam_tfidf_model.predict(X_test)

In [113]:
score=accuracy_score(y_test,y_pred)
print(score)

0.9757847533632287


In [114]:
from sklearn.metrics import classification_report
print(classification_report(y_pred,y_test))

              precision    recall  f1-score   support

       False       0.84      1.00      0.91       141
        True       1.00      0.97      0.99       974

    accuracy                           0.98      1115
   macro avg       0.92      0.99      0.95      1115
weighted avg       0.98      0.98      0.98      1115



In [115]:
from sklearn.metrics import confusion_matrix
cr = confusion_matrix(y_pred, y_test)
cr

array([[141,   0],
       [ 27, 947]])